//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.25 at 10:13:31 AM EET 
//


package ua.nure.entities;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ua.nure.entities package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ua.nure.entities
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Player }
     * 
     */
    public Player createPlayer() {
        return new Player();
    }

    /**
     * Create an instance of {@link GetPlayersByCountryRequest }
     * 
     */
    public GetPlayersByCountryRequest createGetPlayersByCountryRequest() {
        return new GetPlayersByCountryRequest();
    }

    /**
     * Create an instance of {@link PlayerInfo }
     * 
     */
    public PlayerInfo createPlayerInfo() {
        return new PlayerInfo();
    }

    /**
     * Create an instance of {@link Stadium }
     * 
     */
    public Stadium createStadium() {
        return new Stadium();
    }

    /**
     * Create an instance of {@link GetPlayersCountResponse }
     * 
     */
    public GetPlayersCountResponse createGetPlayersCountResponse() {
        return new GetPlayersCountResponse();
    }

    /**
     * Create an instance of {@link FindPlayerRequest }
     * 
     */
    public FindPlayerRequest createFindPlayerRequest() {
        return new FindPlayerRequest();
    }

    /**
     * Create an instance of {@link UpdateTeamRequest }
     * 
     */
    public UpdateTeamRequest createUpdateTeamRequest() {
        return new UpdateTeamRequest();
    }

    /**
     * Create an instance of {@link Info }
     * 
     */
    public Info createInfo() {
        return new Info();
    }

    /**
     * Create an instance of {@link Players }
     * 
     */
    public Players createPlayers() {
        return new Players();
    }

    /**
     * Create an instance of {@link GetPlayersByCountryResponse }
     * 
     */
    public GetPlayersByCountryResponse createGetPlayersByCountryResponse() {
        return new GetPlayersByCountryResponse();
    }

    /**
     * Create an instance of {@link DeleteTeamRequest }
     * 
     */
    public DeleteTeamRequest createDeleteTeamRequest() {
        return new DeleteTeamRequest();
    }

    /**
     * Create an instance of {@link Coach }
     * 
     */
    public Coach createCoach() {
        return new Coach();
    }

    /**
     * Create an instance of {@link FindPlayerResponse }
     * 
     */
    public FindPlayerResponse createFindPlayerResponse() {
        return new FindPlayerResponse();
    }

    /**
     * Create an instance of {@link Sponsors }
     * 
     */
    public Sponsors createSponsors() {
        return new Sponsors();
    }

    /**
     * Create an instance of {@link CoachInfo }
     * 
     */
    public CoachInfo createCoachInfo() {
        return new CoachInfo();
    }

    /**
     * Create an instance of {@link GetMaxPlayerCostRequest }
     * 
     */
    public GetMaxPlayerCostRequest createGetMaxPlayerCostRequest() {
        return new GetMaxPlayerCostRequest();
    }

    /**
     * Create an instance of {@link DeletePlayerRequest }
     * 
     */
    public DeletePlayerRequest createDeletePlayerRequest() {
        return new DeletePlayerRequest();
    }

    /**
     * Create an instance of {@link FindTeamRequest }
     * 
     */
    public FindTeamRequest createFindTeamRequest() {
        return new FindTeamRequest();
    }

    /**
     * Create an instance of {@link GetPlayersCountRequest }
     * 
     */
    public GetPlayersCountRequest createGetPlayersCountRequest() {
        return new GetPlayersCountRequest();
    }

    /**
     * Create an instance of {@link FindTeamResponse }
     * 
     */
    public FindTeamResponse createFindTeamResponse() {
        return new FindTeamResponse();
    }

    /**
     * Create an instance of {@link Sponsor }
     * 
     */
    public Sponsor createSponsor() {
        return new Sponsor();
    }

    /**
     * Create an instance of {@link Teams }
     * 
     */
    public Teams createTeams() {
        return new Teams();
    }

    /**
     * Create an instance of {@link GetMaxPlayerCostResponse }
     * 
     */
    public GetMaxPlayerCostResponse createGetMaxPlayerCostResponse() {
        return new GetMaxPlayerCostResponse();
    }

    /**
     * Create an instance of {@link StadiumInfo }
     * 
     */
    public StadiumInfo createStadiumInfo() {
        return new StadiumInfo();
    }

    /**
     * Create an instance of {@link Team }
     * 
     */
    public Team createTeam() {
        return new Team();
    }

}
