//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.25 at 10:13:31 AM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://entities.nure.ua")
package ua.nure.entities;
