//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 07:37:10 PM EET 
//


package ua.nure.entities;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for Team complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Team">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="general" type="{http://entities.nure.ua}Info"/>
 *         &lt;element name="players" type="{http://entities.nure.ua}Players"/>
 *         &lt;element name="coach" type="{http://entities.nure.ua}Coach"/>
 *         &lt;element name="sponsors" type="{http://entities.nure.ua}Sponsors"/>
 *         &lt;element name="stadium" type="{http://entities.nure.ua}Stadium"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Team", propOrder = {
    "general",
    "players",
    "coach",
    "sponsors",
    "stadium"
})
public class Team {

    @XmlElement(required = true)
    protected Info general;
    @XmlElement(required = true)
    protected Players players;
    @XmlElement(required = true)
    protected Coach coach;
    @XmlElement(required = true)
    protected Sponsors sponsors;
    @XmlElement(required = true)
    protected Stadium stadium;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the general property.
     * 
     * @return
     *     possible object is
     *     {@link Info }
     *     
     */
    public Info getGeneral() {
        return general;
    }

    /**
     * Sets the value of the general property.
     * 
     * @param value
     *     allowed object is
     *     {@link Info }
     *     
     */
    public void setGeneral(Info value) {
        this.general = value;
    }

    /**
     * Gets the value of the players property.
     * 
     * @return
     *     possible object is
     *     {@link Players }
     *     
     */
    public Players getPlayers() {
        return players;
    }

    /**
     * Sets the value of the players property.
     * 
     * @param value
     *     allowed object is
     *     {@link Players }
     *     
     */
    public void setPlayers(Players value) {
        this.players = value;
    }

    /**
     * Gets the value of the coach property.
     * 
     * @return
     *     possible object is
     *     {@link Coach }
     *     
     */
    public Coach getCoach() {
        return coach;
    }

    /**
     * Sets the value of the coach property.
     * 
     * @param value
     *     allowed object is
     *     {@link Coach }
     *     
     */
    public void setCoach(Coach value) {
        this.coach = value;
    }

    /**
     * Gets the value of the sponsors property.
     * 
     * @return
     *     possible object is
     *     {@link Sponsors }
     *     
     */
    public Sponsors getSponsors() {
        return sponsors;
    }

    /**
     * Sets the value of the sponsors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sponsors }
     *     
     */
    public void setSponsors(Sponsors value) {
        this.sponsors = value;
    }

    /**
     * Gets the value of the stadium property.
     * 
     * @return
     *     possible object is
     *     {@link Stadium }
     *     
     */
    public Stadium getStadium() {
        return stadium;
    }

    /**
     * Sets the value of the stadium property.
     * 
     * @param value
     *     allowed object is
     *     {@link Stadium }
     *     
     */
    public void setStadium(Stadium value) {
        this.stadium = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
